### ISSUE TITLE
Failed to cache the components in the workspace (click for another attempt)

### ISSUE THREAD

**Issue by lucksjb** [leosj29/jsf-primefaces-intellisense#11]
I had this error, and I had this error and even running "**JSF and Primefaces cache**" the problem persists.
how to solve this.

tnx advanced.

Luck

**Comment by leosj29** [comment]
Hi, I haven't been able to see or replicate what you're talking about, could you provide me with some guidance on how to replicate it?

**Comment by lucksjb** [comment]
Error:
![Erro](https://user-images.githubusercontent.com/12874607/232477495-b4cc1824-fe24-46e0-88f3-a6835c143e6c.gif)

VSCode version:
![image](https://user-images.githubusercontent.com/12874607/232478629-85dc548b-9ed5-4115-9e97-b05c8402c8f7.png)

do u have some log to see detailed error?
tnx advanced

**Comment by melloware** [comment]
I am seeing the same error in my console.

**Comment by lucksjb** [comment]
Can I help u in something?

**Comment by melloware** [comment]
You can do the following and it happened to me.

1. git clone: https://github.com/primefaces/primefaces-test
2. Follow these instructions: https://github.com/primefaces/primefaces-test/blob/master/vscode-quickstart.md

In VS Code I am getting the same errors as above and no IntelliSense is happening.

**Comment by FlipWarthog** [comment]
I'm able to reproduce it as well in both my main install and the reproducer @melloware posted. I've also confirmed if I downgrade to v1.7.0 of the extension, the issue is not present.

**Comment by leosj29** [comment]
Hi!,
 I have identified the problem, apparently the path of the component files is incorrect. I'm already working on the issue.

Thanks!

**Comment by melloware** [comment]
Just tested 1.8.1 and it seems fixed for me!
