### ISSUE TITLE
GoTo Definitions for JSF beans in EL expressions in xhtml files

### ISSUE THREAD

**Issue by per-steinar** [leosj29/jsf-primefaces-intellisense#17]
I'm looking into adding support for GoToDefinition for JSF bean references in xhtml files. Is that something that you would be interested in adding to this extenson?

**Comment by leosj29** [comment]
Hello, sorry for being so distant, I took some time off. Yes, that's something I consider important. I had done some research on it, but at that time, I couldn't get it to work.
