### ISSUE TITLE
Refactor extention loading to simplify adding new frameworks

### ISSUE THREAD

**Issue by per-steinar** [leosj29/jsf-primefaces-intellisense#4]
I have looked into extension.ts to make it easier to add new frameworks. Take a look et https://github.com/per-steinar/jsf-primefaces-intellisense/tree/refactor
It's not tested enough, so it shouldn't be merged in the current state. I have also created a small Powershell (running on Ubuntu) script to generate the component definition files if you are interested.

**Comment by leosj29** [comment]
It's a great idea. I see that it greatly simplifies the work and eliminates code duplication. As for the script to generate the component definition files, it's very interesting, since I currently do it manually.

**Comment by leosj29** [comment]
Hello, I added a version similar to the one proposed by you to the source code. I have uploaded a new version (1.4.0), thank you very much for your contribution.
