### ISSUE TITLE
seems xmlns need to be updated

### ISSUE THREAD

**Issue by nandcep** [leosj29/jsf-primefaces-intellisense#5]
Hi I just found that seems the xmlns incorrect for several tags when I open my JSF project that written on vscode. For JSF 2.2 looks better to use http://xmlns.jcp.org/jsf rather than http://java.sun.com/jsf
e.g f:viewAction is available when I use xmlns:f="http://xmlns.jcp.org/jsf/core" and will not be available if I'm using xmlns:f="http://java.sun.com/jsf/core"

hereby attached when I opened the JSF project using Jetbrains and after use java.sun.com domain the viewAction got a red font color (invalid)
<img width="666" alt="Screen Shot 2022-06-05 at 03 49 14" src="https://user-images.githubusercontent.com/45379524/172025066-55d0ca14-f613-443c-873a-6b4340a57432.png">

and it should be available if I'm using xmlns.jcp.org got a pink font color (valid)
<img width="675" alt="Screen Shot 2022-06-05 at 03 51 30" src="https://user-images.githubusercontent.com/45379524/172025130-6b23d2c3-f0d8-4052-8a7a-dfbed4528c7c.png">

**Comment by leosj29** [comment]
Hi @adinandradrs, thanks for your interest in improving the extension. I was unaware of the namespace update for JSF 2.2. I just added these namespaces and generated a new version. I hope it lives up to expectations.
