### ISSUE TITLE
Add support for jakarta faces

### ISSUE THREAD

**Issue by tmsanchez** [leosj29/jsf-primefaces-intellisense#7]
I want to collaborate to add jakarta faces 4.0 support.  I cloned the repo and I was checking the code.  As I can see because componentes for jakarta.faces.html are the same like http://java.sun.com/jsf/html we only need to add the name space like 

lines 30-31
	{ id: "cc", urls: ["http://java.sun.com/jsf/composite", "http://xmlns.jcp.org/jsf/composite","jakarta.faces.composite"], dataFilename: "cc", uniqueDefinitions: [] },
	{ id: "f", urls: ["http://java.sun.com/jsf/core", "http://xmlns.jcp.org/jsf/core","jakarta.faces.core"], dataFilename: "f", uniqueDefinitions: [] },
	{ id: "h", urls: ["http://java.sun.com/jsf/html", "http://xmlns.jcp.org/jsf/html","jakarta.faces.html"], dataFilename: "h", uniqueDefinitions: [] },
in extensions.ts file

¿or do we need to create json files in data folder for jakarta namespaces?

Thanks

**Comment by leosj29** [comment]
> I want to collaborate to add jakarta faces 4.0 support. I cloned the repo and I was checking the code. As I can see because componentes for jakarta.faces.html are the same like http://java.sun.com/jsf/html we only need to add the name space like
> 
> lines 30-31 { id: "cc", urls: ["http://java.sun.com/jsf/composite", "http://xmlns.jcp.org/jsf/composite","jakarta.faces.composite"], dataFilename: "cc", uniqueDefinitions: [] }, { id: "f", urls: ["http://java.sun.com/jsf/core", "http://xmlns.jcp.org/jsf/core","jakarta.faces.core"], dataFilename: "f", uniqueDefinitions: [] }, { id: "h", urls: ["http://java.sun.com/jsf/html", "http://xmlns.jcp.org/jsf/html","jakarta.faces.html"], dataFilename: "h", uniqueDefinitions: [] }, in extensions.ts file
> 
> ¿or do we need to create json files in data folder for jakarta namespaces?
> 
> Thanks

Hello, thank you for your collaboration.  If the components are exactly the same, it would only apply that change mentioned above.  However if any change, it would be good to specify the json with the namespaces
