### ISSUE TITLE
PrimeFaces Extensions 12.0.6

### ISSUE THREAD

**Issue by melloware** [leosj29/jsf-primefaces-intellisense#9]
Hey love that you are doing this as we have some devs using VS Code now. I am the maintainer of PrimeFaces extensions and would love to see this updated for the latest Taglib of 12.0.6.

Is there anything I can do to help?

**Comment by melloware** [comment]
Also are you doing this in an automated way or by hand?   @FlipWarthog has done something similar for automatically creating the PrimeFlex CSS Intellisense by using a program to parse the CSS and generate the Intellisense.  Are you doing that with these XML taglibs to make it easier to update?  

If not do you want some help?

**Comment by leosj29** [comment]
Hi, thank you for your comments!.

Currently, I'm generating the taglibs manually. I use another app ([https://github.com/leosj29/taglibs-faces-generator](https://github.com/leosj29/taglibs-faces-generator)) to obtain the taglib.xml from git repositories or VDL files directly from the web, and then transform them into JSON format to be read by the extension. 

I'm going to update the extension to include PrimeFaces extensions 12.0.6 and create several parameters to configure it. 

After these changes, I'm going to review @FlipWarthog 's work to try to generate them automatically in future versions, depending on the version referenced in the projects.

**Comment by melloware** [comment]
@FlipWarhog's project is written in Rust and is here: https://github.com/FlipWarthog/css-to-snippets

**Comment by melloware** [comment]
We just added instructions for VS Code for PrimeFaces Test that recommends your plugin by default!  See: https://github.com/primefaces/primefaces-test/blob/master/vscode-quickstart.md


See: https://github.com/primefaces/primefaces-test/blob/master/.vscode/extensions.json
